"use client";

import { MoralisProvider } from "react-moralis";
import "./globals.css";
import { Titillium_Web } from "next/font/google";
import { Navbar } from "./containers/Navbar";

const APP_ID = process.env.NEXT_PUBLIC_APP_ID || "";

const inter = Titillium_Web({
  subsets: ["latin"],
  weight: ["200", "300", "400", "600", "700", "900"],
});

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
