"use client";

import "./globals.css";
import { Titillium_Web } from "next/font/google";
import { Navbar } from "./containers/Navbar";
import { NextAuthProvider } from "./providers";
import { Config, WagmiConfig, configureChains, createConfig } from "wagmi";
import { sepolia } from "wagmi/chains";
import { publicProvider } from "wagmi/providers/public";
import { PublicClient } from "viem";

const inter = Titillium_Web({
  subsets: ["latin"],
  weight: ["200", "300", "400", "600", "700", "900"],
});

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const { publicClient, webSocketPublicClient } = configureChains(
  [sepolia],
  [publicProvider()]
);

const config = createConfig({
  autoConnect: true,
  publicClient,
  webSocketPublicClient,
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <WagmiConfig config={config}>
          <NextAuthProvider>
            <Navbar />
            {children}
          </NextAuthProvider>
        </WagmiConfig>
      </body>
    </html>
  );
}
